name: Automatic Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          token: ${{ secrets.TEST_REBASE_PAT }}
          fetch-depth: 0 
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_REBASE_PAT }}
      - name: Notify on success
        uses: actions/github-script@v3
        if: success()
        with:
          github-token: ${{secrets.TEST_REBASE_PAT}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Rebase successful'
            })

